# Generated by Django 4.1.6 on 2023-02-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_perfume_description_alter_perfume_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=1000)),
                ('rating', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=('5', 5), max_length=1)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.perfume')),
            ],
        ),
    ]
